name: Deploy Main Website

on:
  push:
    branches:
      - main 
    
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"

            # ensure correct node version
            nvm use 24

            cd BhuviHomes

            echo "Pulling latest code..."
            git pull origin main

            echo "Installing dependencies..."
            pnpm install

            echo "Building Next.js app..."
            pnpm build

            echo "Restarting PM2..."
            pm2 reload bhuvihomes || pm2 start "pnpm start --port 4000" --name bhuvihomes

            echo "Deployment complete"